default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: personal_portfolio_development

test:
  <<: *default
  database: personal_portfolio_test


production:
  <<: *default
  database: personal_portfolio_production
  username: personal_portfolio
  password: <%= ENV['PERSONAL_PORTFOLIO_DATABASE_PASSWORD'] %>
